"""add sima credentials to user

Revision ID: 3116fc4db831
Revises: f114ba21b4f5
Create Date: 2025-06-17 11:58:23.478352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3116fc4db831'
down_revision = 'f114ba21b4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sima_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sima_password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sima_password')
        batch_op.drop_column('sima_username')

    # ### end Alembic commands ###
