"""add evento model

Revision ID: 5077c3db8f00
Revises: 881eb8511ee3
Create Date: 2025-06-15 21:59:04.388898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5077c3db8f00'
down_revision = '881eb8511ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('dia', sa.String(length=10), nullable=True),
    sa.Column('mes_ano', sa.String(length=20), nullable=True),
    sa.Column('curso_nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    # ### end Alembic commands ###
