"""add sima credenciales

Revision ID: f114ba21b4f5
Revises: 517b4ce5c5a2
Create Date: 2025-06-17 11:55:51.537727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f114ba21b4f5'
down_revision = '517b4ce5c5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sima_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sima_password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('sima_password')
        batch_op.drop_column('sima_username')

    # ### end Alembic commands ###
